### ISSUE TITLE
Classification

### ISSUE THREAD

**Issue by sctrueew** [dme-compunet/YOLOv8#10]
Hi, thanks for your work. Is it possible to support classification?

**Comment by dme-compunet** [comment]
Yes, here is a sample code:
```csharp
var image = "path/to/image";

using var predictor = new YoloV8("path/to/model");

var result = predictor.Classify(image);
```

**Comment by sctrueew** [comment]
@dme-compunet Hi, I exported my trained model with this script

`
from ultralytics import YOLO
model = YOLO(r"..\runs\classify\train19\weights\best.pt")
model.export(format='onnx', opset=15, imgsz = 224)
`
and then I used this code for inference:

` void ClassifyDemo(string image1, string model)
   {
      Console.WriteLine();
      Console.WriteLine("================ SEGMENTATION DEMO ================");
      Console.WriteLine();
      Console.WriteLine("Loading model...");
      using var predictor = new YoloV8(model); 
  
      Console.WriteLine("Working...");
      var result = predictor.Classify(image);
  
      Console.WriteLine();
  
      Console.WriteLine($"Result: {result}");
      Console.WriteLine($"Speed: {result.Speed}");
  
      Console.WriteLine();
  
      foreach (var item in result.Probabilities)
      {
          Console.WriteLine($"{item.Class} {item.Confidence}");
      }
  }
`

but the results are not correct.

**Comment by dme-compunet** [comment]
I'm missing details, in a pre-trained model on ImageNet it works great, can you try to understand what the problem is?

**Comment by sctrueew** [comment]
I tested with the Yolo command:
yolo classify predict model=runs\classify\train32\weights\best.onnx source="..\n02099601_1421.JPEG" imgsz=224

The result is correct, but when I run it with C# code, the output is different.

**Comment by xumix** [comment]
> I tested with the Yolo command: yolo classify predict model=runs\classify\train32\weights\best.onnx source="..\n02099601_1421.JPEG" imgsz=224
> 
> The result is correct, but when I run it with C# code, the output is different.

Try sorting by `item.Confidence`

**Comment by NBarile** [comment]
anyone find the solution ? 

I have the same issue, it's incomprehensible ....
