### ISSUE TITLE
How to use the model in a multithreaded application

### ISSUE THREAD

**Issue by oneprofittips** [dme-compunet/YOLOv8#16]
How to use the model in a multithreaded application? Is it possible to create an asp net core singleton and use the Detect method? Will it not give errors in predictions?

**Comment by dme-compunet** [comment]
@oneprofittips I think it should work well in multithreaded mode, if you see any problems then give feedback here.

**Comment by oneprofittips** [comment]
Here is a singleton service I create and use it in my application.  Is everything right?
`public class TestServise
{
    private readonly YoloV8 _predictor;
    private readonly Random _rnd;
    private static readonly string modelFile = "smalls.onnx";
    public TestServise(IConfiguration configuration)
    {
        _predictor = new YoloV8(modelFile);
        var con = configuration.GetValue<float?>("Confidence.smalls.onnx");
        if (con.HasValue)
            _predictor.Parameters.Confidence = con.Value;
        _rnd = new Random();
    }
    public List<string> GetObjects(string base64Img)
    {
        var findRes = _predictor.Detect(new ImageSelector(Convert.FromBase64String(base64Img)));
        if (findRes == null)
            return null;
        var res = new List<string>();
        var boxws = findRes.Boxes.ToList().OrderBy(x => x.Bounds.X);
        foreach (var b in boxws)
        {
            res.Add(b.Class.Name);
        }
        return res.Distinct().ToList();
    }
}`

**Comment by dme-compunet** [comment]
@oneprofittips Yes, it should work without problems.
