### ISSUE TITLE
How to package YOLOv8 as DLL and call it

### ISSUE THREAD

**Issue by mc-lgt** [dme-compunet/YOLOv8#18]
Hello, the author. Do you know how to package YOLOv8 as DLL and then call it

**Comment by dme-compunet** [comment]
This project is also available as nuget package, you can add one of these nuget packages, [YoloV8](https://www.nuget.org/packages/YoloV8) or [YoloV8.Gpu](https://www.nuget.org/packages/YoloV8.Gpu)

Does this help you or do you need something else?

**Comment by mc-lgt** [comment]
May I ask how to turn YOLOv8 into a nuget package.

**Comment by mc-lgt** [comment]
Is this the website "www.nuget. org/packages/YoloV8"
