### ISSUE TITLE
After upgrading from version 1.4 to version 1.5-1.6, it became very difficult to detect.

### ISSUE THREAD

**Issue by oneprofittips** [dme-compunet/YOLOv8#19]
I have 2 trained models, and on average there are 4-7 objects in the image, version 1.4 works stably and finds everything, after updating to new versions on the same models, the quality dropped, on one model instead of 4-7 it finds 0-1 objects. I return everything to version 1.4, everything finds.

**Comment by dme-compunet** [comment]
Try setting `YoloV8Parameters.ProcessWithOriginalAspectRatio` to `true`, this gives improved results, the default has changed to `false` due https://github.com/dme-compunet/YOLOv8/issues/13

In any case, I planning in the next version to change the `ProcessWithOriginalAspectRatio` default value to `true`.

**Comment by oneprofittips** [comment]
Thanks for the help.

**Comment by FunJoo** [comment]
@dme-compunet 
In addition to the vessel project, I have many other detection projects, and in many cases, `ProcessWithOriginalAspectRatio` indeed needs to be set to `true`.
