### ISSUE TITLE
Model not supported

### ISSUE THREAD

**Issue by uri-el99** [dme-compunet/YOLOv8#22]
Hello author, hope you are doing well.

I am currently trying to use the NuGet Package but I am getting some troubles.
I am starting with programming so I´m a bigginer, I used your code reference but I get this: System.InvalidOperationException: 'The loaded model does not support this task' and I do not why, I´ve searched for some solutions but I´m still stuck.
Can you help me out? I´d highly apreciate.
![image](https://github.com/dme-compunet/YOLOv8/assets/147002782/5b738fc9-48b0-4ac7-acfd-974e2b813d39)

**Comment by dme-compunet** [comment]
Hello @uri-el99, this exception is thrown because you are trying to perform detection from a model whose task is not 'detect'. YOLOv8 has models for several tasks, you must make sure that the inference you make matches to task of the model. (you can see the model task in the [Netron](https://github.com/lutzroeder/netron) tool)

**Comment by uri-el99** [comment]
> Hello @uri-el99, this exception is thrown because you are trying to perform detection from a model whose task is not 'detect'. YOLOv8 has models for several tasks, you must make sure that the inference you make matches to task of the model. (you can see the model task in the [Netron](https://github.com/lutzroeder/netron) tool)

I greatly appreciate your response and help on this problem, thank you very much for that observation.
Hoping not to take up your time, I would like to know if you can help me with another question.
I want to load an image in WindowsForms through an OpneFileDialog and display the image in another one, but already with the results obtained by the model. Do you know how I can make the conversion from System.Drawing.Image to Compunet.YoloV8.ImageSelector?

**Comment by FunJoo** [comment]
```
var ofd = new Microsoft.Win32.OpenFileDialog();
if (ofd.ShowDialog() == true)
{
    var image = Compunet.YoloV8.ImageSelector(ofd.FileName)
}
```

**Comment by uri-el99** [comment]
> ```
> var ofd = new Microsoft.Win32.OpenFileDialog();
> if (ofd.ShowDialog() == true)
> {
>     var image = Compunet.YoloV8.ImageSelector(ofd.FileName)
> }
> ```

Hi @FunJoo hope I am not disturbing you. Rephrasing my question, how can I display the result in a PictureBox?
I want to open an image that is displayed in a PictureBox, and, subsequently, that selected image is analysed and the result is displayed in another PictureBox. I hope you can help me a bit and sorry for the inconvenience.

**Comment by FunJoo** [comment]
Hi, @uri-el99  I do not use WinForm, but I can provide you with a method given by ChatGPT4.
``` C#
public static SixLabors.ImageSharp.Image<Rgb24> ConvertToImageSharpImage(System.Drawing.Image systemDrawingImage)
{
    using MemoryStream memoryStream = new MemoryStream();
    systemDrawingImage.Save(memoryStream, System.Drawing.Imaging.ImageFormat.Png);
    memoryStream.Seek(0, SeekOrigin.Begin);
    return SixLabors.ImageSharp.Image.Load<Rgb24>(memoryStream);
}

public static System.Drawing.Image ConvertToSystemDrawingImage(SixLabors.ImageSharp.Image<Rgb24> imageSharpImage)
{
    using MemoryStream memoryStream = new MemoryStream();
    imageSharpImage.Save(memoryStream, new SixLabors.ImageSharp.Formats.Png.PngEncoder());
    memoryStream.Seek(0, SeekOrigin.Begin);
    return System.Drawing.Image.FromStream(memoryStream);
}
```
When encountering situations where `Compunet.YoloV8.ImageSelector` is needed, you can directly use `SixLabors.ImageSharp.Image`.

**Comment by uri-el99** [comment]
Thanks for supporting me, and hoping you can help me just one more time, now I face another problem.

Once converting from System.Drawing to SixLabors, a new issue exist when var result is used in Image.Load.
![image](https://github.com/dme-compunet/YOLOv8/assets/147002782/714d61dc-9fe4-4d27-bfa6-ec4666e668d0)

A solution was using (Stream)
![image](https://github.com/dme-compunet/YOLOv8/assets/147002782/179fe8e1-4787-40ac-8ee6-999a53c8d84a)

But then when running program, a new error is shown
![image](https://github.com/dme-compunet/YOLOv8/assets/147002782/66315c6d-befb-4bd0-b37a-0ba81f057bbd)

Do you know any solution for this? Sorry for the inconvenience, I'm just learning in this new world of programming.

**Comment by uri-el99** [comment]
@FunJoo Thanks for all your support, using the information you provided, I was able to solve that problem, and, although others came up later, I was able to solve them.
I appreciate the time you took to find a solution, thank you very much. best regards!
