### ISSUE TITLE
System.InvalidOperationException: 'The loaded model does not support this task'

### ISSUE THREAD

**Issue by NBarile** [dme-compunet/YOLOv8#23]
Hello ! 

I have the same problem as this issue : https://github.com/dme-compunet/YOLOv8/issues/22

But I don't understand how to resolve it ... 

If someone can help me, I'll really appreciate ^^

**Comment by NBarile** [comment]
![image](https://github.com/dme-compunet/YOLOv8/assets/48790575/0d521662-39a6-43af-8398-48b1d0c93bf9)

I add to you the image of my issue if needed

**Comment by dme-compunet** [comment]
You are trying to perform pose estimation from a model whose task is not
'pose estimation', you must load a matching model to infer a pose estimate.
