### ISSUE TITLE
How to enable GPU

### ISSUE THREAD

**Issue by monkeycc** [dme-compunet/YOLOv8#32]
![微信截图_20240104103827](https://github.com/dme-compunet/YOLOv8/assets/6490927/bc6e2bff-91cf-4d43-bdaa-9f4c1c2b85e5)

```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

I am a beginner in C #
I don't know how to enable GPU

**Comment by FunJoo** [comment]
Similar questions have been asked in previous issues. 
↓
#11

**Comment by penspanic** [comment]
using var yolo = new YoloV8(new ModelSelector("path", SessionOptions.MakeSessionOptionWithCudaProvider());
Use `SessionOptions.MakeSessionOptionWithCudaProvider())`.

**Comment by monkeycc** [comment]
`using var predictor = new YoloV8(model, SessionOptions.MakeSessionOptionWithCudaProvider(0));`

Problem solved, code modification required
