### ISSUE TITLE
Suggest adding OBB support

### ISSUE THREAD

**Issue by monkeycc** [dme-compunet/YOLOv8#35]
https://docs.ultralytics.com/tasks/obb/#export
Oriented Bounding Boxes Object Detection

**Comment by dme-compunet** [comment]
It's planned for sometime, I don't have much free time so it will take some time to happen, also need an algorithm to calculate IoU for oriented bounding boxes.

If anyone is willing to prepare PR, it would be welcome.

**Comment by bnemetchek2** [comment]
I added a PR for this.  [OBB](https://github.com/dme-compunet/YOLOv8/pull/43)

I can confirm that IoU for OBB is not easy.
