### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by oneprofittips** [dme-compunet/YOLOv8#38]
After updating to version 3.1.0, the error "Index was outside the bounds of the array." when calling DetectAsync

**Comment by ArsiIksait** [comment]
I'm having this problem too. I'm not sure what's going on.
![image](https://github.com/dme-compunet/YOLOv8/assets/63351011/805e8436-9583-496d-864d-ad24f5a00d31)
![31469bdb9f142ed1ddb1cba1cc39da63](https://github.com/dme-compunet/YOLOv8/assets/63351011/4a5b35ff-7d12-4544-a35f-5de78bf76c74)
![9d92b7b12fde70e6181578001d2092d9](https://github.com/dme-compunet/YOLOv8/assets/63351011/bbb2d661-9350-46bd-9e82-6721593d1d2d)

**Comment by ArsiIksait** [comment]
Seems like he sometimes has this problem when he detects a target

**Comment by ArsiIksait** [comment]
I tried downgrading to version 3.0.0 and had no problems
![image](https://github.com/dme-compunet/YOLOv8/assets/63351011/05419e3a-ef28-4d63-8c94-82f2c6c441b9)
![image](https://github.com/dme-compunet/YOLOv8/assets/63351011/6a5b7067-807b-4a16-bf3d-597aa905da19)
![image](https://github.com/dme-compunet/YOLOv8/assets/63351011/1dd5c52a-b1c9-4a41-ae3e-02f28f14e181)

**Comment by ArsiIksait** [comment]
I also found that using version 3.0.0 for target identification returned much higher confidence results than using version 3.0.1

Using version 3.0.0:
![image](https://github.com/dme-compunet/YOLOv8/assets/63351011/ddbf9090-40cc-49bc-97a8-6dd43f2bfa6b)
![fa0ea19e7f7ee6332fcaa9f5f556a5f7](https://github.com/dme-compunet/YOLOv8/assets/63351011/a0619794-e433-455b-a0aa-c8e666254abc)

Using version 3.0.1:
![394c297a85d939123a372c6be0687fa7](https://github.com/dme-compunet/YOLOv8/assets/63351011/4d8351da-b2f0-4c1e-9659-cbeedd4f92c4)
![26e80248717ae20fe59ae6be5ff04075](https://github.com/dme-compunet/YOLOv8/assets/63351011/98921176-fbd1-49a5-b6b9-fc1079a34ac5)

So I'm going to use version 3.0.0 and leave 3.0.1 alone

**Comment by dme-compunet** [comment]
I apologize for the bug, it was fixed in version 3.1.1
