### ISSUE TITLE
Logic for resizing images to fit the size of the model input data.

### ISSUE THREAD

**Issue by oneprofittips** [dme-compunet/YOLOv8#39]
Add or change in parameter
Mode = originalAspectRatio ? ResizeMode.Max : ResizeMode.Stretch
  method for resizing an image, originalAspectRatio suggests leaving the original size, but in a fluid situation, if the size is 480 x 60, for example, with a model size of 480 x 480, it will stretch the smallest side to fit the size of the model.
Instead of ResizeMode.Max, I think it’s better to change it to ResizeMode.BoxPad or display these settings in the configuration.

**Comment by dme-compunet** [comment]
Sorry for the late reply, what are you trying to get from BoxPad? It is
exactly like the current behavior, in the current state the input tensor is
created in the size of the model, the pixels of the image are copied to the
center of the tensor and the margins remain with a value of 0.0 which means
black color. (BoxPad will only add time of copying the black pixels of the
padding)

**Comment by oneprofittips** [comment]
For example, I do training on a size of 480x480 and pass 480x80 to the input of the Detect model, and I get 0 matches.
If I train at 480 and pass 480x80 to the input during training, and with Detect 480x80 I get a more or less good result.
It turns out that the resize is stretching 80 pixels by 480 pixels, and not adding empty pixels.

**Comment by dme-compunet** [comment]
I don't know how to solve your problem, but I don't think BoxPad will help,
if YoloV8Parameters.KeepOriginalAspectRatio is set to true, the aspect
ratio is kept as in the original.
Try to fork this repo and see if changing ResizeMode.Max to
ResizeMode.BoxPad will solve your problem, if it solves your problem,
please share here.
