### ISSUE TITLE
Getting lower confidence values

### ISSUE THREAD

**Issue by sabihoshi** [dme-compunet/YOLOv8#42]
I am getting a lower confidence value, Typically lower with the one from python. The model is not OBB.
Even with the image resized to 640x640 or 640 with the same aspect ratio.

Ultralytics YOLOv8.1.20 🚀 Python-3.10.11 torch-2.2.1+cu118 CPU (AMD Ryzen 9 7950X 16-Core Processor)
```
yolo predict model="...\best.onnx" source="...\cavity.jpg" save_txt=True save_conf=True device=cpu
```
![cavity](https://github.com/dme-compunet/YOLOv8/assets/25006819/ee283b74-f3e0-4a24-9865-4c8c50b10e13)
![resized](https://github.com/dme-compunet/YOLOv8/assets/25006819/4629fbb6-0138-4f79-8ac5-b6b6e1692613)

.Net 8.0 SDK
YoloV8.GPU 3.1.1
```cs
using Compunet.YoloV8;
using Compunet.YoloV8.Plotting;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;

var image = @"...\cavity.jpg";
var model = @"...\best.onnx";

using var predictor = new YoloV8(model);

using var origin = Image.Load(image);
using var resizedImage = origin.Clone(ctx => ctx.Resize(new ResizeOptions
{
    Size = new Size(640, 640),
    Mode = ResizeMode.Max
}));

var result = await predictor.DetectAsync(origin);
using var plotted = await result.PlotImageAsync(origin);
plotted.Save(Path.Combine("output", Path.GetFileName(image)));
```
![cavity](https://github.com/dme-compunet/YOLOv8/assets/25006819/00ad5e8e-7697-4d52-868a-c9e53b276172)
![cavity](https://github.com/dme-compunet/YOLOv8/assets/25006819/b62bfec4-7183-4f1d-b077-0c0b9b0dc7ce)

So you can test the model yourself
[weights.zip](https://github.com/dme-compunet/YOLOv8/files/14499290/weights.zip)

**Comment by dme-compunet** [comment]
Hi @sabihoshi 
In the last published version there is a problem with the non-max suppression algorithm, which caused some problems (and also decrease in the confidence percentage), version `4.0.0` will be published soon and it is likely that these problems will be solved there.

**Comment by sabihoshi** [comment]
Thank you. I can confirm `v4.0.0` solved my issues. Cheers!
