### ISSUE TITLE
Load Image

### ISSUE THREAD

**Issue by Elliot8212** [dme-compunet/YOLOv8#44]
Cannot use Image or Bitmap, it necessary need to be a path.

**Comment by bobezlolz** [comment]
you can convert the bitmap/image to a byte array and pass it to the predictor

`static byte[] ToByteArray(System.Drawing.Image imageIn, System.Drawing.Imaging.ImageFormat fmt)
{
    if (imageIn != null)
    {
        using (MemoryStream ms = new MemoryStream())
        {
            imageIn.Save(ms, fmt);
            return ms.ToArray();
        }
    }

    return new byte[] { };
}`

**Comment by dme-compunet** [comment]
`Bitmap` is only in Windows, you can use the code in the comment above.
