### ISSUE TITLE
some pictures does not show transparent boxes

### ISSUE THREAD

**Issue by Mystogun** [dme-compunet/YOLOv8#49]
This is the image I'm running the model against

Original Image
![image](https://github.com/dme-compunet/YOLOv8/assets/24925082/95a88be3-fc8e-4a69-be13-78919072dfeb)

I use this code

```csharp
using var platesPredictor = YoloV8Predictor.Create(platesModelPath);
var plateResults = platesPredictor.Detect(new ImageSelector(pictureBox3.ToImageSharpImage()));
using SixLabors.ImageSharp.Image detectedPlateImage = pictureBox3.ToImageSharpImage();
pictureBox6.Image = new Bitmap(new MemoryStream(plateResults.PlotImage(detectedPlateImage).ToArray()));
```

and this is the plotted image

Image after plotting
![image](https://github.com/dme-compunet/YOLOv8/assets/24925082/9c41ad30-05f2-4955-885f-8e063430ac03)

it looks like the boxes are not transparent

I tried to solve it by doing this

```csharp
using var platesPredictor = YoloV8Predictor.Create(platesModelPath);
var plateResults = platesPredictor.Detect(new ImageSelector(pictureBox3.ToImageSharpImage()));
using SixLabors.ImageSharp.Image detectedPlateImage = pictureBox3.ToImageSharpImage();

var detectionOptions = new DetectionPlottingOptions();
detectionOptions.ColorPalette = new Compunet.YoloV8.Plotting.ColorPalette("ff000010");
detectionOptions.BoxBorderThickness = 1;

pictureBox6.Image = new Bitmap(new MemoryStream(plateResults.PlotImage(detectedPlateImage, detectionOptions).ToArray()));
```

it plotes this image, but there are no borders nor labels and confidence
![image](https://github.com/dme-compunet/YOLOv8/assets/24925082/95e704b5-a18e-4454-8beb-9291930ed74c)

--------------------
but the same code(the one without the detectionOptions object) works fine with other pictures
like this one
![image](https://github.com/dme-compunet/YOLOv8/assets/24925082/644eec1e-a756-449c-83da-166b5d095c60)

yet the boxes on some other pictures are not transparent

**Comment by dme-compunet** [comment]
> it plotes this image, but there are no borders nor labels and confidence

Indeed there are labels and borders, but they are not visible due to the poor quality of the image.

A possible solution is to create a canvas of an empty image in the dimensions of the original image (but of a higher quality), draw the blurred image to the canvas and then draw the predictions to the image.
