### ISSUE TITLE
DetectObb is not showing any bounding boxes for object (car in my case)

### ISSUE THREAD

**Issue by aloksharma1** [dme-compunet/YOLOv8#53]
Hello i tried to use yolov8x-obb.onnx with your package because i need the object orientation as well as detection, but even on lowest confidence level i am not getting any detection.
can you share an example for obb? here is my code, hopefully i am following the process correctly:

```
private readonly YoloV8Predictor _predictor= YoloV8Predictor.Create(@"G:\Dotnet\Desktop\Windows\ATTSystem\ATTSystem\Assets\yolov8x-obb.onnx");

using var image = Image.Load<Rgb48>(frame.ToBytes());
var result = _predictor.DetectObb(image); //no bounding boxes tried car /bus/truck/van images
```

**Comment by dme-compunet** [comment]
odd.... I will check it on my side soon.

**Comment by dme-compunet** [comment]
Can you attach the picture to reproduce the problem?

**Comment by aloksharma1** [comment]
Hi i am using video with opencv to extract frame by frame images, i have extracted the images from my video example for your testing. you can use these to see why i am not getting anything on obb, fyi these same images work with segmentation and detect algo.
what i need now is to not only segment the vehicle but also see its direction.
![car-parking-1_1](https://github.com/dme-compunet/YOLOv8/assets/4345706/1ba2597f-3cbf-44af-b1d9-b08e8c888c27)
![car-parking-1_2](https://github.com/dme-compunet/YOLOv8/assets/4345706/4218da52-0b11-4cc0-9676-60d22f019601)
![car-parking-1_3](https://github.com/dme-compunet/YOLOv8/assets/4345706/d25942bb-efd5-43e3-96ca-86c35ee605a4)
![car-parking-1_4](https://github.com/dme-compunet/YOLOv8/assets/4345706/ab810cc0-2d11-4a6d-be6c-2c4446836453)

**Comment by dme-compunet** [comment]
@aloksharma1 you will probably need to train your own model for your need, because the pre-trained model is suitable for satellite photos and such (DOTAv1 dataset), not for low-altitude photos.

**Comment by aloksharma1** [comment]
> @aloksharma1 you will probably need to train your own model for your need, because the pretrained model is suitable for satellite photos and such (DOTAv1 dataset), not for low-altitude photos.

oh understood, then my next issue is i need to mix segmentation technique with oob what do you suggest a single custom trained model or using 2 separate models?

**Comment by dme-compunet** [comment]
I do not know. You should ask here: https://github.com/ultralytics/ultralytics
