### ISSUE TITLE
Processing video files

### ISSUE THREAD

**Issue by XuanSAMA1872** [dme-compunet/YOLOv8#55]
Hi author!

I am a C# beginner. I follow the standard code and this model handles images very well, and I want to estimate posture for a video.
Can this model handle this kind of problem?
If the model works, can you give an example？

Thank's!

**Comment by dme-compunet** [comment]
No, currently the library does not support video, you can use ffmpeg to
extract frames from the video, and predict the frames. you can then
reassemble them to a video file.
