### ISSUE TITLE
can't set configuration for create a predictor

### ISSUE THREAD

**Issue by GuenKainto** [dme-compunet/YOLOv8#56]
Hi,
![image](https://github.com/dme-compunet/YOLOv8/assets/109414890/50f1c188-0e44-4fd1-8f7e-e52958ede57b)
How can i set Configuration, it's internal  so i can't create  a model

my code look like :
![image](https://github.com/dme-compunet/YOLOv8/assets/109414890/bcd753c3-6db3-408f-8050-bae4ad38d32e)

**Comment by aloksharma1** [comment]
here check this

```
_predictor = YoloV8Predictor.Create("yolov8x.onnx")); //path to model
using var image = Image.Load<Rgb48>(imageData.ToBytes());
var result = _predictor.Detect(image);
if (result != null)
{
    foreach (var box in result.Boxes)
    {
       //draw or do your work here
    }
}
```

should be easy to setup.

**Comment by dme-compunet** [comment]
@GuenKainto 
```csharp
using var predictor = YoloV8Builder.CreateDefaultBuilder()
                                   .UseOnnxModel("path/to/model.onnx")
                                   .WithConfiguration(configuration => 
                                   {
                                       configuration.Confidence = 3.5f,
                                       configuration.IoU = ...
                                   })
                                   .Build();
```

**Comment by GuenKainto** [comment]
> @GuenKainto
> 
> ```cs
> using var predictor = YoloV8Builder.CreateDefaultBuilder()
>                                    .UseOnnxModel("path/to/model.onnx")
>                                    .WithConfiguration(configuration => 
>                                    {
>                                        configuration.Confidence = 3.5f,
>                                        configuration.IoU = ...
>                                    })
>                                    .Build();
> ```

Thankyou for reply ^.^ 
and i found an another way 

private static YoloV8Predictor predictor = YoloV8Predictor.Create(Path.Combine(Environment.CurrentDirectory, "Assets\\model\\best.onnx"));
        public static async Task<Image> PredictAsync(Image image, float? iou, float? confidence)
        {
            YoloV8Configuration config = new YoloV8Configuration();
            config.IoU = iou ?? 0.45f;
            config.Confidence = confidence ?? 0.3f;
            ImageSelector imageSelector = new(image);
            var result = await predictor.DetectAsync(imageSelector, config);
            return await result.PlotImageAsync(image);
        }
Is this okay ?

**Comment by dme-compunet** [comment]
> Is this okay ?

Yes, it's only meant to pass configuration for a one prediction.
