### ISSUE TITLE
Where can I change the iou and conference of the model from the beginning?

### ISSUE THREAD

**Issue by s1030512149** [dme-compunet/YOLOv8#6]
Sorry to bother again.
Here is my code:
var predictor = new YoLoV8(modelpath);
predictor.Parameter.IoU = 0.15f;
predictor.Parameter.Confidence = 0.4f.

It works. But can i change the value of iou and conf from the first line: var predictor = new YoLoV8(modelpath, ......)
Can u help me with that, thanks a lot.

**Comment by dme-compunet** [comment]
Currently there is no such option, why is it important for you to initialize it from the constructor?

**Comment by s1030512149** [comment]
> Currently there is no such option, why is it important for you to initialize it from the constructor?

OK, thanks for your reply. Actually, it is not important for me from the initialization. If there is no option, that's fine. Thans again.
