### ISSUE TITLE
ProcessMask may throw Exception when box`s height is 0

### ISSUE THREAD

**Issue by bianchh** [dme-compunet/YoloV8#60]
when i do a segment job,  IndexedBoundingBox may have 0 height, cause a Exception
![image](https://github.com/dme-compunet/YOLOv8/assets/42956643/f7412bfa-1754-4817-aff1-030265c8d917)

**Comment by dme-compunet** [comment]
I will check it soon..

**Comment by dme-compunet** [comment]
@bianchh can you share model and a picture for testing?

**Comment by bianchh** [comment]
> @bianchh can you share model and a picture for testing?

Sure，can i have your email address ？

**Comment by dme-compunet** [comment]
Yes: compunet.develope@gmail.com
