### ISSUE TITLE
The given key 'author' was not present in the dictionary

### ISSUE THREAD

**Issue by mchenryXD** [dme-compunet/YOLOv8#61]
![image](https://github.com/dme-compunet/YOLOv8/assets/77257565/22ec132a-85eb-402e-80a5-2e1a4ba2d9cf)

why need author

**Comment by bianchh** [comment]
![image](https://github.com/dme-compunet/YOLOv8/assets/42956643/9852371d-673e-41d4-b831-cc9b71239d51)
我没遇到过这个报错，检查一下你的模型

**Comment by dme-compunet** [comment]
This repo currently only supports `YOLOv8` models converted to onnx with the `ultralytics` library
