### ISSUE TITLE
How to change the 'line_width' parameter when I get a plotted image?

### ISSUE THREAD

**Issue by NewerZeus** [dme-compunet/YoloV8#63]
I am using the code 'using var plotted = await result.PlotImageAsync(image);' to get a plotted image, but I wish the line_width can be smaller.

Thank you!

**Comment by dme-compunet** [comment]
Yes, you can. check: https://github.com/dme-compunet/YOLOv8/blob/main/Source/YoloV8/Plotting/DetectionPlottingOptions.cs
