### ISSUE TITLE
high memory usage if we make it run in every 5 seconds

### ISSUE THREAD

**Issue by areytechai** [dme-compunet/YoloV8#69]
![image](https://github.com/user-attachments/assets/9f3d1e7f-25f5-4039-9b71-74e6fb7f0aa1)

  async Task PredictAndSaveAsync(YoloPredictor predictor, string image)
 {
     var path = $"./images/{image}";

     var task = predictor.Metadata.Task;

     Console.WriteLine($"Running '{image}' (test: {task})...");

     var result = await predictor.PredictAndSaveAsync(path);

     Console.WriteLine($"Result: {result}");
     Console.WriteLine($"Speed:  {result.Speed}");

     Console.WriteLine();
     localClient.Publish("coreAICheck", Encoding.UTF8.GetBytes("ONLINE" + DateTime.Now.ToString()));
     localClient.Publish("AREYLightAICheck", Encoding.UTF8.GetBytes(result.ToString()));

     
     // Gerekirse çöp toplayıcısını çağırın
     GC.Collect();
     GC.WaitForPendingFinalizers();

 }

            try
            {

                //Console.WriteLine("Loading pose estimation model...");
                //using var posePredictor = new YoloPredictor("./models/yolov8n-pose-uint8.onnx");

                //Console.WriteLine("Loading detection model...");
                //using var detectPredictor = new YoloPredictor("./models/yolov8n-uint8.onnx");

                Console.WriteLine("Loading segmentation model...");
                using var segmentPredictor = new YoloPredictor("./models/yolov8n-seg-uint8.onnx");

                //Console.WriteLine("Loading classification model...");
                //using var classifyPredictor = new YoloPredictor("./models/yolov8n-cls-uint8.onnx");

                Console.WriteLine();

                //await PredictAndSaveAsync(posePredictor, "arx.jpg");
                //await PredictAndSaveAsync(posePredictor, "arx.jpg");

                //await PredictAndSaveAsync(detectPredictor, "arx.jpg");
           //     await PredictAndSaveAsync(detectPredictor, "arx.jpg");

                await PredictAndSaveAsync(segmentPredictor, "arx.jpg");

                //await PredictAndSaveAsync(classifyPredictor, "arx.jpg");
                //await PredictAndSaveAsync(classifyPredictor, "arx.jpg");

                segmentPredictor?.Dispose();

                segmentPredictor.Dispose();

                // Gerekirse çöp toplayıcısını çağırın
                GC.Collect();
                GC.WaitForPendingFinalizers();

                //await PredictAndSaveAsync(classifyPredictor, "arx.jpg");
            }
            catch (Exception ex)
            {

            }

it keeps higher and higher,

is there an easy step to make it fix?

**Comment by areytechai** [comment]
<img width="1920" alt="Screenshot 2024-09-23 at 20 52 58" src="https://github.com/user-attachments/assets/2b70466b-77b9-45b2-be73-006962dc5901">

the single thing takes lots of memory, how we can make it clear? gc collectors even doesnt work

**Comment by dme-compunet** [comment]
@areytechai Thanks for reporting this, I have now released version `5.0.2` which fixes this memory leak.
