### ISSUE TITLE
Real-time Processing of MJPEG Video Stream using YOLOv8

### ISSUE THREAD

**Issue by areytechai** [dme-compunet/YoloV8#72]
Hi,

I would like to know if it's possible to process the video stream from this MJPEG URL ([video stream](http://94.124.210.59:8083/mjpg/video.mjpg)) in real-time using the YOLOv8 architecture.

Currently, what I'm doing is saving the video frames as JPEG images via VLC, then processing them with YOLOv8 and saving the results. However, this method isn't real-time.

Is there a way to process the video stream directly in real-time? If not, could you suggest some simple alternative methods or best practices to achieve this?

Thanks in advance for your help!

**Comment by dme-compunet** [comment]
I have no experience with this, but I guess the best way is to extract the frames with `ffmpeg` into the `stdout` and then process them with YOLOv8

**Comment by areytechai** [comment]
> I have no experience with this, but I guess the best way is to extract the frames with `ffmpeg` into the `stdout` and then process them with YOLOv8

Thank you! Extracting frames with FFmpeg into stdout and then processing them with YOLOv8 is indeed an effective approach. By the way, when do you plan to incorporate YOLOv11? Additionally, we would like to count the bags being filled at the cat food factory using the camera. Is this possible?

**Comment by dme-compunet** [comment]
>By the way, when do you plan to incorporate YOLOv11?

In general, once Ultralytics supports exporting it to onnx, then I can add support for it, But it's not guaranteed.

>Additionally, we would like to count the bags being filled at the cat food factory using the camera. Is this possible?

Better to ask here: https://github.com/ultralytics/ultralytics
