### ISSUE TITLE
Recommended CUDA and cuDNN versions for ONNX Runtime 1.19.1 in YoloV8.Gpu?

### ISSUE THREAD

**Issue by GordeychikStepan** [dme-compunet/YoloV8#74]
Hello,

I am currently using ONNX Runtime with GPU support in a project based on the YoloV8.Gpu library. However, I am encountering a `LoadLibrary failed with error 126` when trying to use `onnxruntime_providers_cuda.dll`. I have CUDA 12.6 and cuDNN v8.9.7 installed. Could you please let me know which versions of CUDA and cuDNN are recommended for compatibility with ONNX Runtime version 1.19.1 in this context?

Thank you in advance!

**Comment by dme-compunet** [comment]
Try:
CUDA: 12.2
cuDNN: 9.3
