### ISSUE TITLE
I'm getting an Out of Range error when trying to initialize my predictor

### ISSUE THREAD

**Issue by mcQk** [dme-compunet/YoloV8#76]
I'm using the same path to the model as before but now I'm getting an error when I updated the nuget packet 

System.ArgumentOutOfRangeException: 'Specified argument was out of the range of valid values. (Parameter 'Shape must not have negative elements: -1')'

![image](https://github.com/user-attachments/assets/8ef20c2f-63f6-40d8-9b92-9c94bc1b6fbe)

**Comment by dme-compunet** [comment]
I know this problem from YOLO-World V2, it will be fixed soon, probably in version `5.1.0`
