### ISSUE TITLE
Is C # recognition much slower than Python?

### ISSUE THREAD

**Issue by bbhxwl** [dme-compunet/YoloV8#88]
Is C # recognition much slower than Python?
C# 304ms
python  3ms+64.4ms
![image](https://github.com/user-attachments/assets/4d93b6ec-6d4e-4ab8-8557-f3a64f793b03)
![image](https://github.com/user-attachments/assets/6f314907-43d6-41a6-9ab9-8273bc3b91ad)

**Comment by dme-compunet** [comment]
You don't measure performance like that, certainly not in debugging mode.

A starting point for performance testing could be the following code:

```csharp
using var predictor = new YoloPredictor("path/to/model.onnx");

for (int i = 0; i < 20; i++)
{
    var result = predictor.Detect("path/to/image.jpg");

    Console.WriteLine(result.Speed);
}
```
